# Generated by Django 6.0 on 2025-12-20 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tattoo_salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя клиента")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 звезда"),
                            (2, "2 звезды"),
                            (3, "3 звезды"),
                            (4, "4 звезды"),
                            (5, "5 звезд"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(verbose_name="Отзыв")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tattoo_salon.master",
                        verbose_name="Мастер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
